#spring:
#  application:
#    name: eureka-server
#  cloud:
#    bootstrap:
#      enabled: true
#
#
#server:
#  port: 8761
#
#
#eureka:
#  instance:
#    hostname: 127.0.0.1
#  #    statusPageUrlPath: ${server.servletPath}/info
#  #    healthCheckUrlPath: ${server.servletPath}/health
#  client:
#    registerWithEureka: false
#    fetchRegistry: false
#    serviceUrl:
#      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
